import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'ar';
type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  showLanguagePopup: boolean;
  setShowLanguagePopup: (show: boolean) => void;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'hero.title': 'Trouvez un livreur près de chez vous',
    'hero.subtitle': 'La première plateforme de mise en relation entre clients et livreurs locaux au Maroc',
    'hero.cta': 'Rechercher un livreur',
    'hero.selectCity': 'Choisir une ville',
    'nav.home': 'Accueil',
    'nav.couriers': 'Livreurs',
    'nav.becomeCourier': 'Devenir livreur',
    'nav.login': 'Connexion',
    'courier.available': 'Disponible',
    'courier.unavailable': 'Indisponible',
    'courier.contact': 'Contacter',
    'courier.viewProfile': 'Voir le profil',
    'courier.deliveries': 'livraisons',
    'courier.verified': 'Vérifié',
    'become.title': 'Devenez livreur partenaire',
    'become.subtitle': 'Rejoignez notre réseau de livreurs et augmentez vos revenus',
    'become.cta': 'Commencer maintenant',
    'become.benefit1': 'Choisissez vos zones',
    'become.benefit2': 'Gérez votre disponibilité',
    'become.benefit3': 'Revenus flexibles',
    'footer.rights': 'Tous droits réservés',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.terms': 'Conditions',
    'cities.casablanca': 'Casablanca',
    'cities.rabat': 'Rabat',
    'cities.marrakech': 'Marrakech',
    'cities.tanger': 'Tanger',
    'cities.fes': 'Fès',
    'vehicle.moto': 'Moto',
    'vehicle.velo': 'Vélo',
    'vehicle.voiture': 'Voiture',
    'language.choose': 'Choisissez votre langue',
    'couriers.title': 'Livreurs disponibles',
    'couriers.subtitle': 'Trouvez le livreur idéal pour vos besoins',
    'couriers.noCouriers': 'Aucun livreur disponible pour le moment',
    'register.title': 'Créer votre compte livreur',
    'register.subtitle': 'Rejoignez notre réseau et commencez à livrer',
    'register.fullName': 'Nom complet',
    'register.fullNamePlaceholder': 'Entrez votre nom complet',
    'register.email': 'Email',
    'register.emailPlaceholder': 'votre@email.com',
    'register.phone': 'Numéro de téléphone',
    'register.phonePlaceholder': '+212 6XX XXX XXX',
    'register.city': 'Ville',
    'register.selectCity': 'Choisir une ville',
    'register.password': 'Mot de passe',
    'register.passwordPlaceholder': 'Minimum 6 caractères',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.confirmPasswordPlaceholder': 'Répétez votre mot de passe',
    'register.submit': 'Créer mon compte',
    'register.loading': 'Création en cours...',
    'register.hasAccount': 'Déjà un compte ?',
    'register.login': 'Se connecter',
    'register.success.title': 'Compte créé !',
    'register.success.message': 'Vérifiez votre email pour activer votre compte.',
    'register.error.title': 'Erreur',
    'register.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'register.error.nameTooShort': 'Le nom doit contenir au moins 2 caractères',
    'register.error.invalidEmail': 'Email invalide',
    'register.error.invalidPhone': 'Numéro de téléphone invalide',
    'register.error.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'register.error.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'register.error.emailExists': 'Cet email est déjà utilisé',
    'register.error.cityRequired': 'Veuillez sélectionner une ville',
    'register.error.vehicleRequired': 'Veuillez sélectionner un type de véhicule',
    'register.vehicleType': 'Type de véhicule',
    'register.selectVehicle': 'Sélectionner un véhicule',
    'login.title': 'Connexion livreur',
    'login.subtitle': 'Accédez à votre espace livreur',
    'login.email': 'Email',
    'login.emailPlaceholder': 'votre@email.com',
    'login.password': 'Mot de passe',
    'login.passwordPlaceholder': 'Votre mot de passe',
    'login.submit': 'Se connecter',
    'login.loading': 'Connexion...',
    'login.noAccount': 'Pas encore de compte ?',
    'login.register': 'S\'inscrire',
    'login.success.title': 'Bienvenue !',
    'login.success.message': 'Connexion réussie.',
    'login.error.title': 'Erreur de connexion',
    'login.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'login.error.invalidEmail': 'Email invalide',
    'login.error.passwordRequired': 'Mot de passe requis',
    'login.error.invalidCredentials': 'Email ou mot de passe incorrect',
    'login.error.emailNotConfirmed': 'Veuillez confirmer votre email avant de vous connecter',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.subtitle': 'Gérez votre profil et votre disponibilité',
    'dashboard.logout': 'Déconnexion',
    'dashboard.deliveries': 'Livraisons',
    'dashboard.rating': 'Note',
    'dashboard.available': 'Disponible',
    'dashboard.unavailable': 'Indisponible',
    'dashboard.status': 'Statut',
    'dashboard.verified': 'Vérifié',
    'dashboard.notVerified': 'Non vérifié',
    'dashboard.account': 'Compte',
    'dashboard.availability': 'Disponibilité',
    'dashboard.availableForDelivery': 'Disponible pour les livraisons',
    'dashboard.availabilityDescription': 'Activez pour apparaître dans les recherches',
    'dashboard.visibleToClients': 'Vous êtes visible par les clients',
    'dashboard.hiddenFromClients': 'Vous êtes masqué des recherches',
    'dashboard.availableNow': 'Vous êtes disponible',
    'dashboard.unavailableNow': 'Vous êtes indisponible',
    'dashboard.availableMessage': 'Les clients peuvent maintenant vous trouver',
    'dashboard.unavailableMessage': 'Vous n\'apparaissez plus dans les recherches',
    'dashboard.profile': 'Mon profil',
    'dashboard.fullName': 'Nom complet',
    'dashboard.phone': 'Téléphone',
    'dashboard.city': 'Ville',
    'dashboard.vehicleType': 'Type de véhicule',
    'dashboard.bio': 'Bio',
    'dashboard.bioPlaceholder': 'Décrivez-vous en quelques mots...',
    'dashboard.saveProfile': 'Enregistrer',
    'dashboard.saving': 'Enregistrement...',
    'dashboard.saved': 'Enregistré',
    'dashboard.profileUpdated': 'Votre profil a été mis à jour',
    'dashboard.error': 'Erreur',
    'dashboard.updateError': 'Impossible de mettre à jour',
    'dashboard.gps': 'Position GPS',
    'dashboard.gpsDescription': 'Partagez votre position pour apparaître dans les recherches à proximité',
    'dashboard.enableGps': 'Activer le GPS',
    'dashboard.updateGps': 'Actualiser',
    'dashboard.gpsActive': 'Position activée',
    'dashboard.gpsActiveDescription': 'Vous êtes visible dans les recherches à proximité',
    'dashboard.gpsNotActive': 'Position non configurée',
    'dashboard.locationSaved': 'Position enregistrée',
    'dashboard.locationSavedMessage': 'Vous apparaîtrez dans les recherches à proximité',
    'dashboard.gpsError': 'Impossible d\'obtenir votre position',
    'dashboard.gpsNotSupported': 'La géolocalisation n\'est pas supportée',
    'dashboard.gettingLocation': 'Localisation...',
    'dashboard.disableGps': 'Désactiver',
    'dashboard.locationDisabled': 'GPS désactivé',
    'dashboard.locationDisabledMessage': 'Vous n\'apparaîtrez plus dans les recherches à proximité',
    'footer.navigation': 'Navigation',
    'footer.legal': 'Légal',
    'footer.description': 'La plateforme de mise en relation entre clients et livreurs locaux au Maroc.',
    'news.title': 'Nouveautés',
    'news.subtitle': 'Découvrez les dernières actualités et mises à jour de notre plateforme',
    'news.backToHome': 'Retour à l\'accueil',
    'news.backToNews': 'Retour aux actualités',
    'news.noArticles': 'Aucun article pour le moment',
    'news.articleNotFound': 'Article non trouvé',
    'profile.notFound': 'Livreur non trouvé',
    'profile.back': 'Retour',
    'profile.verified': 'Vérifié',
    'profile.availableNow': 'Disponible',
    'profile.unavailable': 'Indisponible',
    'profile.memberSince': 'Membre depuis',
    'profile.about': 'À propos',
    'profile.noInfo': 'Aucune information disponible',
    'profile.deliveryZones': 'Zones de livraison',
    'profile.reviews': 'Avis clients',
    'profile.reviewsSoon': 'Avis bientôt disponibles...',
    'profile.stats': 'Statistiques',
    'profile.deliveries': 'Livraisons',
    'profile.rating': 'Note',
    'profile.status': 'Statut',
    'profile.gpsActive': 'Actif',
    'profile.gpsInactive': 'Inactif',
    'profile.contactNow': 'Contactez maintenant',
    'profile.freeQuote': 'Obtenez un devis gratuit pour votre livraison',
    'profile.sendMessage': 'Envoyer un message',
    'profile.call': 'Appeler',
    'search.backToHome': 'Retour à l\'accueil',
    'search.nearbyTitle': 'Livreurs près de vous',
    'search.cityTitle': 'Livreurs à',
    'search.loading': 'Chargement...',
    'search.available': 'livreurs disponibles',
    'search.total': 'au total',
    'search.availableNow': 'disponibles maintenant',
    'search.filter': 'Filtrer:',
    'search.all': 'Tous',
    'search.availableOnly': 'Disponibles uniquement',
    'search.verifiedOnly': 'Vérifiés uniquement',
    'search.veryClose': 'Très proches de vous',
    'search.lessThan1km': 'À moins de 1 km',
    'search.otherCouriers': 'Autres livreurs',
    'search.noCouriers': 'Aucun livreur trouvé',
    'search.tryIncreaseRadius': 'Essayez d\'augmenter le rayon de recherche ou de modifier vos filtres',
    'search.tryModifyFilters': 'Essayez de modifier vos filtres ou de rechercher dans une autre ville',
    'search.resetFilters': 'Réinitialiser les filtres',
    'blacklist.title': 'Liste noire',
    'blacklist.subtitle': 'Gérez les numéros bloqués',
    'changePassword.title': 'Changer le mot de passe',
    'changePassword.description': 'Entrez votre nouveau mot de passe ci-dessous.',
    'changePassword.newPassword': 'Nouveau mot de passe',
    'changePassword.newPasswordPlaceholder': 'Minimum 6 caractères',
    'changePassword.confirmPassword': 'Confirmer le mot de passe',
    'changePassword.confirmPasswordPlaceholder': 'Répétez le mot de passe',
    'changePassword.submit': 'Changer le mot de passe',
    'changePassword.saving': 'Enregistrement...',
    'changePassword.cancel': 'Annuler',
    'changePassword.success.title': 'Mot de passe modifié',
    'changePassword.success.message': 'Votre mot de passe a été mis à jour avec succès.',
    'changePassword.error.title': 'Erreur',
    'changePassword.error.generic': 'Une erreur est survenue. Veuillez réessayer.',
    'changePassword.error.tooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'changePassword.error.mismatch': 'Les mots de passe ne correspondent pas',
    'dashboard.changePassword': 'Changer le mot de passe',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes là pour répondre à vos questions et vous accompagner.',
    'contact.name': 'Nom complet',
    'contact.namePlaceholder': 'Votre nom',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'votre@email.com',
    'contact.subject': 'Sujet',
    'contact.subjectPlaceholder': 'De quoi s\'agit-il ?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Écrivez votre message ici...',
    'contact.send': 'Envoyer le message',
    'contact.sending': 'Envoi en cours...',
    'contact.success.title': 'Message envoyé',
    'contact.success.message': 'Nous avons bien reçu votre message. Nous vous répondrons dans les plus brefs délais.',
    'contact.error.nameRequired': 'Le nom est requis',
    'contact.error.emailRequired': 'L\'email est requis',
    'contact.error.invalidEmail': 'Email invalide',
    'contact.error.subjectRequired': 'Le sujet est requis',
    'contact.error.messageRequired': 'Le message est requis',
    'contact.error.messageTooShort': 'Le message doit contenir au moins 10 caractères',
    'contact.info.title': 'Informations',
    'contact.info.email': 'Email',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.hours': 'Horaires',
    'contact.info.hoursValue': 'Lun - Sam : 9h - 18h',
    'contact.info.address': 'Adresse',
    'contact.info.addressValue': 'Casablanca, Maroc',
    'contact.back': 'Retour',
    'app.title': 'Téléchargez notre application mobile',
    'app.subtitle': 'Retrouvez tous les livreurs près de chez vous directement depuis votre téléphone. Rapide, simple et toujours à portée de main.',
    'app.feature1': 'Recherche de livreurs en temps réel',
    'app.feature2': 'Notifications instantanées',
    'app.feature3': 'Suivi GPS des livreurs',
    'app.feature4': 'Interface simple et intuitive',
    'app.downloadOn': 'Disponible sur',
    'app.googlePlay': 'Google Play',
    'app.getItOn': 'Télécharger sur',
  },
  ar: {
    'hero.title': 'لقا ليفرور قريب منك',
    'hero.subtitle': 'أول بلاطفورم فالمغرب كتربط بين الكليان و الليفرورات المحليين',
    'hero.cta': 'قلب على ليفرور',
    'hero.selectCity': 'ختار مدينة',
    'nav.home': 'الرئيسية',
    'nav.couriers': 'الليفرورات',
    'nav.becomeCourier': 'ولي ليفرور',
    'nav.login': 'كونيكسيون',
    'courier.available': 'موجود',
    'courier.unavailable': 'ماشي موجود',
    'courier.contact': 'تواصل معاه',
    'courier.viewProfile': 'شوف البروفيل',
    'courier.deliveries': 'توصيلات',
    'courier.verified': 'موثوق',
    'become.title': 'ولي ليفرور شريك معانا',
    'become.subtitle': 'نضم لشبكتنا ديال الليفرورات وزيد فالدخل ديالك',
    'become.cta': 'بدا دابا',
    'become.benefit1': 'ختار المناطق ديالك',
    'become.benefit2': 'كونطرولي الوقت ديالك',
    'become.benefit3': 'دخل مرن',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.about': 'شكون حنا',
    'footer.contact': 'تواصل معانا',
    'footer.terms': 'الشروط',
    'cities.casablanca': 'كازا',
    'cities.rabat': 'الرباط',
    'cities.marrakech': 'مراكش',
    'cities.tanger': 'طنجة',
    'cities.fes': 'فاس',
    'vehicle.moto': 'موطور',
    'vehicle.velo': 'بيسكليط',
    'vehicle.voiture': 'طوموبيل',
    'language.choose': 'ختار اللغة ديالك',
    'couriers.title': 'الليفرورات الموجودين',
    'couriers.subtitle': 'لقا الليفرور اللي كيناسبك',
    'couriers.noCouriers': 'ما كاين حتا ليفرور دابا',
    'register.title': 'كري الكونط ديالك كليفرور',
    'register.subtitle': 'نضم لشبكتنا وبدا التوصيل',
    'register.fullName': 'السمية الكاملة',
    'register.fullNamePlaceholder': 'دخل السمية الكاملة ديالك',
    'register.email': 'الإيميل',
    'register.emailPlaceholder': 'your@email.com',
    'register.phone': 'رقم التيليفون',
    'register.phonePlaceholder': '+212 6XX XXX XXX',
    'register.city': 'المدينة',
    'register.selectCity': 'ختار مدينة',
    'register.password': 'الباسوورد',
    'register.passwordPlaceholder': '6 حروف على الأقل',
    'register.confirmPassword': 'أكد الباسوورد',
    'register.confirmPasswordPlaceholder': 'عاود دخل الباسوورد',
    'register.submit': 'كري الكونط ديالي',
    'register.loading': 'كنكريو...',
    'register.hasAccount': 'عندك كونط؟',
    'register.login': 'كونيكتا',
    'register.success.title': 'تكرا الكونط!',
    'register.success.message': 'شوف الإيميل ديالك باش تأكد الكونط.',
    'register.error.title': 'خطأ',
    'register.error.generic': 'وقع مشكل. عاود حاول.',
    'register.error.nameTooShort': 'السمية خاصها تكون على الأقل 2 حروف',
    'register.error.invalidEmail': 'الإيميل ماشي صحيح',
    'register.error.invalidPhone': 'رقم التيليفون ماشي صحيح',
    'register.error.passwordTooShort': 'الباسوورد خاصها تكون على الأقل 6 حروف',
    'register.error.passwordMismatch': 'الباسووردات ماشي بحال بحال',
    'register.error.emailExists': 'هاد الإيميل مستعمل',
    'register.error.cityRequired': 'ختار مدينة',
    'register.error.vehicleRequired': 'ختار نوع الڤيكول',
    'register.vehicleType': 'نوع الڤيكول',
    'register.selectVehicle': 'ختار ڤيكول',
    'login.title': 'كونيكسيون ديال الليفرور',
    'login.subtitle': 'دخل للإسباس ديالك',
    'login.email': 'الإيميل',
    'login.emailPlaceholder': 'your@email.com',
    'login.password': 'الباسوورد',
    'login.passwordPlaceholder': 'الباسوورد ديالك',
    'login.submit': 'كونيكتا',
    'login.loading': 'كنكونيكتاو...',
    'login.noAccount': 'ماعندكش كونط؟',
    'login.register': 'سجل دابا',
    'login.success.title': 'مرحبا!',
    'login.success.message': 'كونيكسيون ناجحة.',
    'login.error.title': 'خطأ فالكونيكسيون',
    'login.error.generic': 'وقع مشكل. عاود حاول.',
    'login.error.invalidEmail': 'الإيميل ماشي صحيح',
    'login.error.passwordRequired': 'الباسوورد ضرورية',
    'login.error.invalidCredentials': 'الإيميل ولا الباسوورد غالطين',
    'login.error.emailNotConfirmed': 'أكد الإيميل ديالك قبل ما تكونيكتا',
    'dashboard.welcome': 'مرحبا',
    'dashboard.subtitle': 'جيري البروفيل ديالك والتوفر ديالك',
    'dashboard.logout': 'ديكونيكتا',
    'dashboard.deliveries': 'التوصيلات',
    'dashboard.rating': 'النوط',
    'dashboard.available': 'موجود',
    'dashboard.unavailable': 'ماشي موجود',
    'dashboard.status': 'الحالة',
    'dashboard.verified': 'موثوق',
    'dashboard.notVerified': 'ماشي موثوق',
    'dashboard.account': 'الكونط',
    'dashboard.availability': 'التوفر',
    'dashboard.availableForDelivery': 'موجود للتوصيل',
    'dashboard.availabilityDescription': 'أكتيڤي باش تبان فالريشيرش',
    'dashboard.visibleToClients': 'الكليان كيشوفوك',
    'dashboard.hiddenFromClients': 'ماكتبانش فالريشيرش',
    'dashboard.availableNow': 'راك موجود دابا',
    'dashboard.unavailableNow': 'راك ماشي موجود دابا',
    'dashboard.availableMessage': 'الكليان يقدرو يلقاوك دابا',
    'dashboard.unavailableMessage': 'ماغاديش تبان فالريشيرش',
    'dashboard.profile': 'البروفيل ديالي',
    'dashboard.fullName': 'السمية الكاملة',
    'dashboard.phone': 'التيليفون',
    'dashboard.city': 'المدينة',
    'dashboard.vehicleType': 'نوع الڤيكول',
    'dashboard.bio': 'البيو',
    'dashboard.bioPlaceholder': 'عرف براسك فشي كلمات...',
    'dashboard.saveProfile': 'سجل',
    'dashboard.saving': 'كنسجلو...',
    'dashboard.saved': 'تسجل',
    'dashboard.profileUpdated': 'البروفيل ديالك تحدث',
    'dashboard.error': 'خطأ',
    'dashboard.updateError': 'ماقدرناش نحدثو',
    'dashboard.gps': 'البلاصة GPS',
    'dashboard.gpsDescription': 'شارك البلاصة ديالك باش تبان فالريشيرش اللي قريبين',
    'dashboard.enableGps': 'أكتيڤي GPS',
    'dashboard.updateGps': 'حدّث',
    'dashboard.gpsActive': 'البلاصة مفعّلة ✓',
    'dashboard.gpsActiveDescription': 'راك كتبان عند الناس اللي قريبين منك',
    'dashboard.gpsNotActive': 'البلاصة ماشي محددة',
    'dashboard.locationSaved': 'البلاصة تسجلات',
    'dashboard.locationSavedMessage': 'غادي تبان فالريشيرش اللي قريبين',
    'dashboard.gpsError': 'ماقدرناش نلقاو البلاصة ديالك',
    'dashboard.gpsNotSupported': 'GPS ماشي مدعوم',
    'dashboard.gettingLocation': 'كنقلبو على البلاصة...',
    'dashboard.disableGps': 'طفّي',
    'dashboard.locationDisabled': 'GPS تطفى',
    'dashboard.locationDisabledMessage': 'ماغاديش تبان فالريشيرش اللي قريبين',
    'footer.navigation': 'التنقل',
    'footer.legal': 'قانوني',
    'footer.description': 'البلاطفورم اللي كتربط بين الكليان والليفرورات المحليين فالمغرب.',
    'news.title': 'الأخبار والمستجدات',
    'news.subtitle': 'شوف آخر الأخبار والتحديثات ديال البلاطفورم ديالنا',
    'news.backToHome': 'رجع للرئيسية',
    'news.backToNews': 'رجع للأخبار',
    'news.noArticles': 'ماكاينش شي مقال دابا',
    'news.articleNotFound': 'المقال ماكاينش',
    'profile.notFound': 'الليفرور ماكاينش',
    'profile.back': 'رجوع',
    'profile.verified': 'موثوق',
    'profile.availableNow': 'موجود دابا',
    'profile.unavailable': 'ماشي موجود',
    'profile.memberSince': 'عضو من',
    'profile.about': 'معلومات',
    'profile.noInfo': 'ماكاينش معلومات',
    'profile.deliveryZones': 'مناطق التوصيل',
    'profile.reviews': 'التقييمات',
    'profile.reviewsSoon': 'التقييمات غادي تجي قريبا...',
    'profile.stats': 'الإحصائيات',
    'profile.deliveries': 'التوصيلات',
    'profile.rating': 'النوط',
    'profile.status': 'الحالة',
    'profile.gpsActive': 'مفعّل',
    'profile.gpsInactive': 'ماشي مفعّل',
    'profile.contactNow': 'تواصل دابا',
    'profile.freeQuote': 'خد ديفي مجاني للتوصيل ديالك',
    'profile.sendMessage': 'صيفط ميساج',
    'profile.call': 'عيّط',
    'search.backToHome': 'رجع للرئيسية',
    'search.nearbyTitle': 'الليفرورات القريبين منك',
    'search.cityTitle': 'الليفرورات فـ',
    'search.loading': 'كنحملو...',
    'search.available': 'ليفرور موجود',
    'search.total': 'المجموع',
    'search.availableNow': 'موجودين دابا',
    'search.filter': 'فلتر:',
    'search.all': 'الكل',
    'search.availableOnly': 'الموجودين فقط',
    'search.verifiedOnly': 'الموثوقين فقط',
    'search.veryClose': 'قريبين بزاف منك',
    'search.lessThan1km': 'أقل من 1 كم',
    'search.otherCouriers': 'ليفرورات خرين',
    'search.noCouriers': 'ما لقيناش شي ليفرور',
    'search.tryIncreaseRadius': 'زيد فالنطاق ولا بدّل الفلاتر',
    'search.tryModifyFilters': 'بدّل الفلاتر ولا قلّب فمدينة خرى',
    'search.resetFilters': 'رجّع الفلاتر',
    'blacklist.title': 'اللائحة السوداء',
    'blacklist.subtitle': 'جيري الأرقام المحظورة',
    'changePassword.title': 'بدّل الباسوورد',
    'changePassword.description': 'دخل الباسوورد الجديدة.',
    'changePassword.newPassword': 'الباسوورد الجديدة',
    'changePassword.newPasswordPlaceholder': '6 حروف على الأقل',
    'changePassword.confirmPassword': 'أكد الباسوورد',
    'changePassword.confirmPasswordPlaceholder': 'عاود دخل الباسوورد',
    'changePassword.submit': 'بدّل الباسوورد',
    'changePassword.saving': 'كنسجلو...',
    'changePassword.cancel': 'إلغاء',
    'changePassword.success.title': 'الباسوورد تبدلات',
    'changePassword.success.message': 'الباسوورد ديالك تحدثات بنجاح.',
    'changePassword.error.title': 'خطأ',
    'changePassword.error.generic': 'وقع مشكل. عاود حاول.',
    'changePassword.error.tooShort': 'الباسوورد خاصها تكون على الأقل 6 حروف',
    'changePassword.error.mismatch': 'الباسووردات ماشي بحال بحال',
    'dashboard.changePassword': 'بدّل الباسوورد',
    'contact.title': 'تواصل معانا',
    'contact.subtitle': 'حنا هنا باش نجاوبو على الأسئلة ديالك ونساعدوك.',
    'contact.name': 'السمية الكاملة',
    'contact.namePlaceholder': 'السمية ديالك',
    'contact.email': 'الإيميل',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.subject': 'الموضوع',
    'contact.subjectPlaceholder': 'على شنو بغيتي تهضر؟',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'كتب الرسالة ديالك هنا...',
    'contact.send': 'صيفط الرسالة',
    'contact.sending': 'كنصيفطو...',
    'contact.success.title': 'الرسالة تصيفطات',
    'contact.success.message': 'وصلاتنا الرسالة ديالك. غادي نجاوبوك فأقرب وقت.',
    'contact.error.nameRequired': 'السمية ضرورية',
    'contact.error.emailRequired': 'الإيميل ضروري',
    'contact.error.invalidEmail': 'الإيميل غالط',
    'contact.error.subjectRequired': 'الموضوع ضروري',
    'contact.error.messageRequired': 'الرسالة ضرورية',
    'contact.error.messageTooShort': 'الرسالة خاصها تكون على الأقل 10 حروف',
    'contact.info.title': 'المعلومات',
    'contact.info.email': 'الإيميل',
    'contact.info.whatsapp': 'واتساب',
    'contact.info.hours': 'أوقات العمل',
    'contact.info.hoursValue': 'الاثنين - السبت : 9 - 18',
    'contact.info.address': 'العنوان',
    'contact.info.addressValue': 'كازابلانكا، المغرب',
    'contact.back': 'رجع',
    'app.title': 'حمّل التطبيق ديالنا',
    'app.subtitle': 'لقا الليفرورات القراب منك مباشرة من التيليفون ديالك. سريع، بسيط ودايما فيدك.',
    'app.feature1': 'قلّب على الليفرورات فالوقت الحقيقي',
    'app.feature2': 'نوتيفيكاسيون فورية',
    'app.feature3': 'تتبع GPS ديال الليفرورات',
    'app.feature4': 'واجهة بسيطة وسهلة',
    'app.downloadOn': 'متوفر على',
    'app.googlePlay': 'Google Play',
    'app.getItOn': 'حمّل من',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('fr');
  const [showLanguagePopup, setShowLanguagePopup] = useState(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null;
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    } else {
      setShowLanguagePopup(true);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    setShowLanguagePopup(false);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider
      value={{ language, direction, setLanguage, t, showLanguagePopup, setShowLanguagePopup }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
