import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';

export interface Article { id: string; title: string; title_ar: string | null; content: string; content_ar: string | null; excerpt: string | null; excerpt_ar: string | null; image_url: string | null; is_published: boolean; published_at: string | null; created_at: string; updated_at: string; author_id: string | null; }

export const useArticles = (publishedOnly = true) => useQuery({ queryKey: ['articles', publishedOnly], queryFn: async () => { let query = supabase.from('articles').select('*').order('published_at', { ascending: false, nullsFirst: false }); if (publishedOnly) query = query.eq('is_published', true); const { data, error } = await query; if (error) throw error; return data as Article[]; } });
export const useArticle = (id: string) => useQuery({ queryKey: ['article', id], queryFn: async () => { const { data, error } = await supabase.from('articles').select('*').eq('id', id).single(); if (error) throw error; return data as Article; }, enabled: !!id });
export const useCreateArticle = () => { const qc = useQueryClient(); return useMutation({ mutationFn: async (article: { title: string; content: string } & Partial<Omit<Article, 'title' | 'content'>>) => { const { data, error } = await supabase.from('articles').insert([article] as any).select().single(); if (error) throw error; return data; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['articles'] }) }); };
export const useUpdateArticle = () => { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, ...updates }: Partial<Article> & { id: string }) => { const { data, error } = await supabase.from('articles').update(updates as any).eq('id', id).select().single(); if (error) throw error; return data; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['articles'] }) }); };
export const useDeleteArticle = () => { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => { const { error } = await supabase.from('articles').delete().eq('id', id); if (error) throw error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['articles'] }) }); };
